import { IRulesDto } from '../dtos/Rules.dto';

export const rules: IRulesDto[] = [
  {
    id: '1aaf2209-52af-4a1f-b699-b26896337246',
    created_at: '0001-01-01T00:00:00Z',
    updated_at: '0001-01-01T00:00:00Z',
    name: 'sdk-android-prod',
    domain: '',
    similarityPercentageTolerance: 85,
    hashFeatureWeightTolerance: 0,
    daysToExpireTheContext: 0,
    active: true,
    customerHasPartnerProducts: true,
    rules: [
      {
        ruleId: '56720b4a-8d54-4b28-984e-fa8f4ee01260',
        name: 'Geolocalização Inconsistente',
        nameEn: 'Geolocation Mismatch',
        code: 3,
        index: 0,
        description: 'Verifica se o IP está no país de origem da transação',
        description_en:
          "Verifies if this IP's location matches the transaction's country of origin",
        active: false,
        markAsUnauthorized: false,
        markAsFraud: false,
        isChanged: false,
        isMobile: false,
        customParameters:
          '[{"name":"average_speed_of_travel","value":"151.0003.."}]',
        native: true,
        premium: false,
        codename: 'DEV003',
      },
      {
        ruleId: '56720b4a-8d54-4b28-984e-fa8f4ee01261',
        name: 'Fuso Horário Inconsistente',
        nameEn: 'Timezone Mismatch',
        code: 4,
        index: 0,
        description:
          'Verifica se timezone do IP é o mesmo timezone da transação',
        description_en:
          "Verifies if this IP's timezone matches the transaction's timezone",
        active: false,
        markAsUnauthorized: false,
        markAsFraud: false,
        isChanged: false,
        isMobile: false,
        customParameters: '[]',
        native: true,
        premium: false,
        codename: 'DEV004',
      },
      {
        ruleId: '56720b4a-8d54-4b28-984e-fa8f4ee01263',
        name: 'Cookie sem conformidade',
        nameEn: 'Noncompliant Cookie',
        code: 6,
        index: 0,
        description: 'Cookie sem conformidade',
        description_en: 'Malformed/Bad Cookie',
        active: false,
        markAsUnauthorized: false,
        markAsFraud: false,
        isChanged: false,
        isMobile: false,
        customParameters: '[]',
        native: true,
        premium: false,
        codename: 'DEV006',
      },
      {
        ruleId: '524c8749-2fb3-4cab-951a-2b70506c84b5',
        name: 'Blocklist do Efeito Rede',
        nameEn: 'Network Effect Blocklist',
        code: 9,
        index: 0,
        description:
          'O dispositivo está na blocklist de outros clientes do AllowMe',
        description_en:
          'The device is on the blocklist of other AllowMe customers',
        active: false,
        markAsUnauthorized: false,
        markAsFraud: false,
        isChanged: false,
        isMobile: false,
        customParameters: '[]',
        native: true,
        premium: false,
        codename: 'DEV009',
      },
      
    ],
  }
]